### ISSUE TITLE
Implement data persistence for todo item components

### ISSUE THREAD

**Issue by toomeyDev** [toomeyDev/AngularTodo#2]
Currently todo items are represented as todoComponents, and lack persistence (data is lost when page is refreshed). Application would be much more usable with the addition of data persistence. Using an angular service, should implement methods to store and retrieve user data from the application so that tasks can be defined then resumed as-needed when users leave then return to the site.
- [x] Implement basic data persistence using filler data (use a service to handle GETting and POSTing/PUTting data)
- [x] Convert existing task components to make use of local storage files for data persistence.
- [x] Implement saving and loading methods, control this functionality via button controls for easy access.

**Comment by toomeyDev** [comment]
Using a service which implements a local storage interface makes more sense than using JSON files, might have difficulty getting these files to read/write properly from the browser. Will instead focus on defining an Angular service to store information in Local Storage.

**Comment by toomeyDev** [comment]
c5dcfa608a70df7f238069dfc68abdb64cb32e97 initial framework for data storage service, needs to support GETting, POSTing, PUTting information as TodoItemComponent objects.

**Comment by toomeyDev** [comment]
c9bf028b2c22db3cade873d382e87f77d494f75c Basic get, set, delete and clear functions implemented for data storage service, currently stored values are printed to the console using a series of three buttons to easily test functionality. Stored data persists appropriately, next step is to feed in appropriate data to create new instances of task components and have them persist in the service.

**Comment by toomeyDev** [comment]
Data persistence implemented, todoComponent instances now persist between page refreshes and information can be saved/loaded with button controls for ease of use. Additional reset functionality implemented which brings application back to initial values.
